### ISSUE TITLE
[progress bar] Percentage overflow

### ISSUE THREAD

**Issue by santirodrigo** [odeke-em/drive#177]
Sometimes pull and push operation's percentage bar increase too much, arriving to values over 100%

Here is an output reflecting this (a couple of files moved locally to other directory in the drive folder and a modification on a single file). I don't know when this happens, but here is an output reflecting it:

```
Deletion count 5 dest: 4.51MB
Addition count 5 src: 4.51MB
Modification count 1 src: 29.63KB dest: 28.92KB
Proceed with the changes? [Y/n]:
9484515 / 4757430 [===============================================] 199.36 % 16s
```

As you can see, the final amount of bytes reflected on the left of the progress bar is the sum of deletion+addition+modification count, and the predicted total reflects only the addition count.

**Comment by shaggytwodope** [comment]
@santirodrigo just for @odeke-em sake, what version are you running and method of install?

**Comment by santirodrigo** [comment]
Sorry, I'm running drive on Ubuntu 14.04 64 bits, with go installed from source and drive installed with `go get -u github.com/odeke-em/drive/cmd/drive`

The drive version is 0.1.9 and go version is go1.4.1 linux/amd64

**Comment by shaggytwodope** [comment]
@santirodrigo  Until odeke-em can help ya, try updating to the newest build. 2.0 has been released yesterday. While it may not address your issue directly. It's always ideal to be on the latest release if possible.

**Comment by santirodrigo** [comment]
OK, thank you very much

**Comment by santirodrigo** [comment]
New version installed, but the same behavior is present.

**Comment by odeke-em** [comment]
Thank you @santirodrigo for reporting this and for the information. Thank you very much @shaggytwodope for getting this one.
I will take a look at this in about 8 hours when I get back home.

**Comment by odeke-em** [comment]
@santirodrigo can you confirm that this happens when you have Google Docs + Sheets being pulled?

**Comment by odeke-em** [comment]
@santirodrigo please take a look at PR #182. The issue was that the size of exportable files is not known and hence cannot be put into a manifest for the byte counter. However on every download completion, the byte count was submitted to the progress meter.

**Comment by odeke-em** [comment]
Addressed by PR #182 please get the latest from source.

**Comment by santirodrigo** [comment]
Thanks again for your quick answer and attention!!

**Comment by dolohow** [comment]
Still happens of 0.2.1
```shell
$ drive version
drive version: 0.2.1
Commit Hash: '8f11b79b30145e2c7bcf0428f9e91da605cd1877'
Go Version: go1.4.2
OS: linux/amd64
```
![error](https://cloud.githubusercontent.com/assets/1408564/7621872/7a5f6ade-f9ca-11e4-9300-e6408443e96d.png)

**Comment by santirodrigo** [comment]
That's right! This morning I have found this overflow error again, but now no Google Docs are involved: an example is shown on the image below.
![overflow](https://cloud.githubusercontent.com/assets/11941574/7627243/8bdaf634-fa15-11e4-96c9-8c44dade1329.png)

**Comment by odeke-em** [comment]
Hey folks thanks for reporting this! Actually now this is a separate issue as you'll notice that the deletion count is being logged to the progress bar. Things got broken during a release. I'll dig in more.

**Comment by odeke-em** [comment]
Please take a look at https://github.com/odeke-em/drive/issues/207 and see if the resolution there might be relevant to your case.

**Comment by hut8** [comment]
I just encountered this same bug a few minutes ago. My build is one day old from master on here.

**Comment by malteseunderdog** [comment]
This bug is still present on Ubuntu 16.04.

> drive version: 0.3.5
> Commit Hash: <CURRENT_COMMIT>
> Go Version: <GO_VERSION>
> OS: <OS_INFO>
> BuildTime

I think the problem lies with there being more deletions than insertions.

```
Deletion count 28 dest: 75.24GB
Addition count 27 src: 11.12GB
Proceed with the changes? [Y/n]:Y
 92719509263 / 11936071864 [======================] 776.80% 5m4s
```

And also with negative time!  (yes, drive make moving backwards in time possible!)

![image](https://cloud.githubusercontent.com/assets/502019/15350417/8cc3e88e-1cd9-11e6-8df0-b6882d525ce9.png)

**Comment by odeke-em** [comment]
Thanks y'all for the patience, fixed by https://github.com/odeke-em/drive/pull/784.

**Comment by odeke-em** [comment]
Please get the latest from master by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
