### ISSUE TITLE
Incorrect addition count for .desktop files

### ISSUE THREAD

**Issue by glebm** [odeke-em/drive#292]
I run:

```shell
$ drive pull --hidden=true
Resolving...
+ /Untitled document
+ /Japanese Class @ Google
...
Addition count 49
Proceed with the changes? [Y/n]: 
# No further output
```

All of the files exist as .desktop files, but are still reported for some reason. They are not actually re-downloaded when confirming.

**Comment by odeke-em** [comment]
Hello again @glebm, thanks for reporting this issue. So there is a story behind .desktop files because Google Docs + Sheets can't be downloaded raw but exported, so empty files are touched locally for consistency, and .desktop files are for clickable links. However this is an interesting case, I'll try to look at.

**Comment by glebm** [comment]
Let me know if there is any way I can help debug it. Haven't used Go before but from what I heard GDB is alright.

**Comment by odeke-em** [comment]
Oh for sure, thank you for the offer!

**Comment by odeke-em** [comment]
Hello @glebm, I got some time this evening and investigated the issue you reported and found the issue. I've created a PR to address it. Please take a look at https://github.com/odeke-em/drive/pull/293. Thank you.

**Comment by odeke-em** [comment]
Hello again @glebm, I've addressed this with PR https://github.com/odeke-em/drive/pull/293. Please get the latest from master and thank you for reporting this.

**Comment by glebm** [comment]
Hi, I am still getting the same output as before.
Perhaps I did not get the latest from master correctly? I did:

```sh
$ go get github.com/odeke-em/drive/cmd/drive   
```

**Comment by odeke-em** [comment]
`go get -u github.com/odeke-em/drive/cmd/drive` ;)

**Comment by glebm** [comment]
Yep, same. Also compiled with debugging (gendrive) and the commit hash is latest. The code seems correct, so figuring out how to put a breakpoint with gdb now.

**Comment by glebm** [comment]
I also notice there is https://github.com/derekparker/delve. Any advice on the best debugger to use with Go?

**Comment by glebm** [comment]
I have installed go 1.4.2 (previous using 1.3 - stock on ubuntu 15.04) and can no longer reproduce. It appears this is broken with go1.3 and not go1.4!

**Comment by odeke-em** [comment]
Hello @glebm sorry for the late reply. I was out at lunch. Oh okay, that's crazy, or probably it wasn't updating alright. If that is ambiguous, you can always `cd $GOPATH/src/github.com/odeke-em/drive && git pull origin master && go get github.com/odeke-em/drive/cmd/drive`

**Comment by glebm** [comment]
The commit hash in the src/ was latest, and so was the reported `drive version` commit hash when compiled with debugging. 
No worries about the late replies, we do not have an SLA :smiley:

**Comment by odeke-em** [comment]
Haha @the SLA. I just try to respond as soon as I can :)
