### ISSUE TITLE
On Linux, replace local Google Docs/Sheets files with files containing their url bookmarks.

### ISSUE THREAD

**Issue by dgvirtual** [odeke-em/drive#74]
Are there any plans to make drive behave like the Windows counterpart regarding the Google Documents/Sheets? To have bookmarks pointing to Google Documents/Sheets instead of empty files that we have now? 

Even those empty files that we have now are an advantage compared to what alternatives of drive on Linux (e.g., grive) present. I am hopeful that drive will evolve into a full-featured Linux client for Google Drive.

**Comment by odeke-em** [comment]
Thank you for the faith, I hope we can gain traction and get it right :) Actually someone had requested this feature and I had it in mind. The only problem is that OSX and Linux plus other *NIX based systems don't seem to have a uniform way to create files that are openable via click so I then put it on my back burner, I could be wrong. If you might have some tips towards accomplishing this, please feel free to share them. The empty files are for there consistency's sake and are non pushable upstream.

**Comment by dgvirtual** [comment]
I have added four bookmark files to the shared folder testdir (link
above).  They were produced by dragging bookmark from bookmark editor to
file manager (Dolphin of KDE). The Chrome and Firefox browsers seem to keep
bookmarks in html format. Those are quite bulky, although it must be easy
to trim them down. The KDE browsers produce simple *.desktop files, that
work either with, or without the extension. In all cases the bookmark files
are correctly recognized by KDE file manager and open in the default
browser (in my case – Firefox).

So I think it would not be difficult to implement my suggestion. First
someone has to try the same I did on Gnome, XFCE, Unity environments. I
hope all of them recognize the *.desktop standard, and I would be surprised
if any of those failed to support the Firefox/Chrome standard. And then
choose the better supported one.

On the command line side it might be more complicated. But something like

drive printlink

command could be implemented to extract the link from the desktop/html
file. And even

drive edit file_linking_to_google_document

could be implemented, provided we either have an option during the
authentication phase, making the user specify the default browser command,
or using xdg-open standard, internally calling xdg-open on the link in the
desktop/html file (xdg-open works in Ubuntu, although I heard it is not
universally supported throughout Linux distributions).

See here for discussion on best ways to open web links on the command line:
http://stackoverflow.com/questions/5116473/linux-command-to-open-url-in-default-browser/9293402#9293402

**Comment by odeke-em** [comment]
Sorry for the late reply, I had gone out for quite a bit. Nice, thank you very much for the research. So yes, as you can see none of them are uniform. Everything being commandline based, the simplest way I can think of is for the user to specify the link export format in the config files that drive uses. This format if present will be used to create such files that are exportable on click. So during a pull, if the config is present and link exporting is specified, instead of an empty file, the appropriate fields will be written to that file, and it still should be non upstream pushable.
For example:
* Note this is an imaginary non-standard config:
```shell
$ cd ~/gaccount
$ cat << ! > .gd/link_config.json
> {
>     "create_thumbnail": "true",
>     "default_viewer":     "default.browser",
>     "viewer_per_mimeType": {
>            "png": "....",
>             ...
>     }
>  ...
> }
> !
```

Let me know what you think.

**Comment by dgvirtual** [comment]
I think that would work. I do not think the users will love the idea of
having to edit the configuration file, but that would be a start.

You do not think it is possible, that all distributions – more or less –
recognize the same *.desktop file standard? See here for more about it:

http://standards.freedesktop.org/desktop-entry-spec/latest/index.html#introduction

It is said there that both KDE and Gnome adhere to it. It is the same for
Unity – see https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles
. I see the same is true of XFCE desktop, and since it is merging with
Razor QT, – which is following KDE in certain respects, I expect it to
stick to that  standard in the future.

Therefore, I would expect that making the links of  *.desktop format would
suit most if not all users.

I have no idea about the Mac OS, though. But doesn't MacOS have an official
Google Drive client?

**Comment by odeke-em** [comment]
That is great news! However, I was thinking of creating the clickable file within the formerly zero-byte file. This is because we would be introducing clutter into the user's drive if for each file create an alternate *.desktop file, of which I want to minimize as much. However, this is open to dicussion as well as adaptation as development proceeds.

 With time it should evolve into defaults that some iterations later and hopefully by the time it gets to LINUX users who have never liked editing, the bases will be covered and they'll probably need to edit them only when they want to change the behaviour. However with the new suggestions and documents, this might not be necessary at all.

Yes in deed, MacOS has one, but some folks like myself prefer command line tools. Linux will get priority since the users seem to be the majority, covering MacOS shouldn't be that difficult.

Otherwise thank you again, this is a good start. I'll get started later this evening.

**Comment by Walkman100** [comment]
I would like to add in that on most "modern" linux OSs the `*.desktop` files seem to be the standard, and I'm pretty sure you can omit the .desktop extension and as long as it's correctly formatted, it will still launch the specified URL/URI/location/whatever

**Comment by odeke-em** [comment]
Thank you @Walkman100 for that information, in deed that is what I was hoping for.

**Comment by ikwyl6** [comment]
How are we looking for this to be implemented?

**Comment by odeke-em** [comment]
Hello @ikwyl6, my apologies for the procastination. What happened is that I spent an hour and half trying to read up on how to get the formats in, but got stumped and the next day came from which this left my radar. If someone would be willing to work with me on the formatting for these files, that would be great.

**Comment by dgvirtual** [comment]
Procrastination is ok, especially when you do not own anyone anything :) 

Anyway, the bare minimum content for the *.desktop file with a link would be:

===================
[Desktop Entry]
Icon=text-html
Name=Document name is here
Type=Link
URL=http://www.website.com/
===================

The only three REALLY REALLY required elements would be [Desktop Entry] header, the "Type" element, and the URL element. 

"Name" parameter can be either the file name, or the document name on the Drive - that one could be different from the file name I guess, with special characters etc. In some cases (perhaps not in a file manager window itself - though I will test that tonight) the "Name" might be displayed instead of the file name. "Name" can perhaps be omitted altogether, in case drive does not deal nicely with special characters in document file names.

"Icon" element could point to the generic web link icon (as it does in the example above), or we can create some nice icon(s) specific for google docs. But for the start the generic web link icons would serve. After the basic functionality is in place, we can play with this.

The file should be encoded in UTF-8. 

I am afraid I can offer no help in implementing the functionality, - except by way of testing.

By the way, Google Slides should also be granted the functionality discussed here, besides Docs and Sheets, right?

**Comment by odeke-em** [comment]
Thank you @dgvirtual for this information. Actually I think I had gotten a format similar to what you have but mine didn't work.
That is right, Drawings, Sheets and other formats supported by Google Docs should be too granted the functionality. I am looking forward to getting this in. I'll be about 15 hours because of a class project that is due tonight but after that I should get this in real quick. Please watch your inbox for a call to help in testing. Thank you again.

**Comment by odeke-em** [comment]
Hey folks, please take a look at PR https://github.com/odeke-em/drive/pull/105

**Comment by dgvirtual** [comment]
Sorry, I am not experienced in git, so could someone tell me how to install drive WITH this patch? The regular way would be 

    go get -u github.com/odeke-em/drive/cmd/drive

but it does not install this patch...

**Comment by dgvirtual** [comment]
While I wait for the opportunity to test the patch: I noticed that xdg-open command does not really open the google document upon invoking it in a browser (it opens the file as a text file instead). So, 

    xdg-open GoogleDocument.desktop 

does not work. You have to extract the url from the file manually, which is tedious, and this works, but is even worse: 

    xdg-open $(grep "^URL=" GoogleDocument.desktop |awk -F= '{ print $2}')

Could perhaps a command like 

    drive show GoogleDocument.desktop

be implemented, which would internally invoke xdg-open on the url in *.desktop file, and thus open Google Docs/Sheets/Slides in browser? Alternatively, such command could open any file as it is stored in the cloud in a browser...

**Comment by odeke-em** [comment]
Am doing this via mobile so pardon the typing. To check out the patch:
```shell
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git fetch --all && git checkout linux-file-bookmarking
$ go get github.com/odeke-em/drive/cmd/drive
```
Re-run the last step every time you update the source code.

For the `drive show`, baby steps for now. Once the first request is in, then we can think about this. Also would you mind moving all patch testing comments to the PR #105?

**Comment by odeke-em** [comment]
Fixed by https://github.com/odeke-em/drive/pull/105 that addresses the functionality requested.

**Comment by dgvirtual** [comment]
Since the functionality is very basic and we have not solved the icon problem yet, I have made some very crude icons and the below commands would help put them in place for your file manager to show them on the files representing and pointing to the Google Apps documents. I have made Presentation, document, Spreadsheet and Form document icons, that look somewhat similar to official google icons for these documents. 

First of all, you have to install the updated drive program. 

Then run the commands, that do these things: 

1. Fetch and put in place my developer-art icons :)
2. Force-pull all the google documents to your local hard drive, omitting all the other files from the operation;
3. Change the files somewhat, correcting the Icon= parameter, so they start displaying the proper icons.

Enjoy!

    ## first - cd to your main Drive directory
    ## modify to fit your directory
    cd ~/Drive
    
    ## download some developer-art icons :)
    wget https://googledrive.com/host/0B7N4UaoQWBXiU2NsZGh5NFRacEE -O application-vnd.google-apps.document.png
    wget https://googledrive.com/host/0B7N4UaoQWBXiQTFJUUtST1FwLU0 -O application-vnd.google-apps.form.png
    wget https://googledrive.com/host/0B7N4UaoQWBXiZXJWYTE5eFZGWkU -O application-vnd.google-apps.presentation.png
    wget https://googledrive.com/host/0B7N4UaoQWBXiLWRjSHF2endoZ2c -O application-vnd.google-apps.spreadsheet.png
    
    ## move icons to the appropriate place (works for Debian/Ubuntu, check that your distribution has icons in that place
    mv application-vnd.google-apps.*.png ~/.local/share/icons/
    
    ## now, on Drive, force-pull all the Google Apps document files to get *.desktop file contents into them; 
    ## files are searched recursively and recognized by their size, which is less than ONE byte
    OIFS="$IFS" ; IFS=$'\n'; for i in `find ./ -size -1c -type f` ;  do drive pull -no-prompt=true --force $i ; done;  IFS="$OIFS"
    
    ## replace Icon values in the newly pulled files; files are searched recursively and recognized by their size, which is less than 500 bytes
    OIFS="$IFS" ; IFS=$'\n'; for i in `find ./ -size -500c -type f`;  do sed -i "s/application\/vnd/application-vnd/g" $i ; done;  IFS="$OIFS"

**Comment by odeke-em** [comment]
Oh wow, that is some dedication, thank you! However,  I think moving the icon deficiency to its own issue would be better since I don't think it is a matter that I have expertise on -- licensing. I just want to make sure we aren't violating Google's terms of service and also that the users of drive can be able to use the icons that we may go with, witb protection. I am currently waiting for an answer back from Google Open Source programs + Drive team offices in regards to them providing us with icons to use. Also in case they do not get back to us, if drive were to distribute icons for Linux, we must make sure that the images you have made are good for distribution ie would everyone be allowed to use your original work. What do you think?

**Comment by dgvirtual** [comment]
Everyone is allowed to use my original work, that is fine with me. It is
true those icons mimic to a large extent the original Google Apps icons.
Although both the colours and content is different a little. If need be, I
could make them more different still.

However, I am not sure if it is proper to distribute icons in just one size
(128px) and I do not yet know how to install them properly with the
program. That remains to be done in the future.

2015-03-19 15:49 GMT+02:00 Emmanuel Odeke <notifications@github.com>:

**Comment by ikwyl6** [comment]
You would need to just look at their license. I'm sure it's close or a variant of GPL 2 or 3. There are "Coles notes" websites that explain the unmodified GPL to you (in case you don't want to read it all). 

Or a quick question in the freenode GPL IRC channel. I'm sure there is a FAQ. 

If I have time I will research later this week/wkend. On mobile now.

**Comment by odeke-em** [comment]
@ikwyl6 whose license, Google's or an individual's?
@dgvirtual that sounds great. Concerning icon distribution, if you are in the legal clear concerning these icons, you could make a git repo or even CDN drop, then provide different sizes as well as share with the icon's users the steps that you described previously. Thank you btw for bringing up the issue of *.desktop files for Linux, as well as for the direction and discussion in helping to solve it!

**Comment by ikwyl6** [comment]
Having a quick look here (http://setup.googleapps.com/Home/user-resources/google-icons-and-logos): 

```
Important: These icons and logos are for use only in your organization's internal communications
about Google Apps. By downloading Google Apps icons and logos, you are agreeing to the 
Guidelines for Using Google Brand Features.
```

The "Guidelines for Using Google Brand Features" are here: http://goo.gl/pIFLxm

From the "Things you can do", i think you can use the icons. But the last 4-5 bullet points seem to pertain to this situation about the modification of the icons by @dgvirtual. The way I read it anyways. Hopefully Google gets back to you.

**Comment by odeke-em** [comment]
However, notice that they are talking about an organization but drive is an open source project. And yes, I too see that a whole bunch of the "don't" clauses seem to point to the previous suggestions, but I could be wrong.

**Comment by dgvirtual** [comment]
Ok, I think I do need to make the icons more dissimilar to those Google
Apps use - remove the bent corner first of all, change it into a paper clip
or something similar, maybe add some other graphic element (like the holes
made to fit the paper documents to binders). I will do that during the next
few days. I will only keep similar main colour of each, otherwise there is
no point doing separate icons, we could as well point the Icon parameter to
some icons in a set already on Linux distributions.

**Comment by dgvirtual** [comment]
So I have updated the icons: hopefully they are both different enough and reminiscient enough to the original google icons at the same time. I would hardly take time to set up a repository of my own, as I do not hold them to be of high artistic value. But in case @odeke-em is willing to add them to the source of drive (temporarily, as I am sure more advanced replacements will come shortly), I would be honoured. The source *.xcf icons are to be found in the same directory of Google Drive, right here: https://drive.google.com/open?id=0B7N4UaoQWBXiUS1CcE9EYmw0STQ&authuser=0

**Comment by odeke-em** [comment]
Nice! Thank you @dgvirtual for the hardwork. I would be excited to add them into the source, but unfortunately branding and copyrighting are topics that I do not understand well hence I will have to just get the Google Open Source office to take a look at them before I can add them into drive :( However with the repo from you, I can put a reference to your work as well as kindly ask the distributors to package it along. This way you can make as many updates to the icons as needed without having to recompile or make releases to drive. Our friendly platform package manager @shaggytwodope what do you think?
I appreciate this otherwise!

**Comment by odeke-em** [comment]
@dgvirtual I haven't heard back from Google Open Source programs despite a couple of efforts trying to push for a response. If they get back, maybe we shall see the way forward.
However, in the meantime, I kindly wanted to ask if you could make a pull request to add the icons into drive as you had previously requested.  Probably put them in a directory relative to root called assets/icons. I'd like to see you added on the contributor graphs as well get the commit logged from you to recognize your contribution.
Thank you very much again, for the advocacy and pushing through to get this feature in. I shall be up in about 7 hours and will be getting things ready for the next release.

**Comment by shaggytwodope** [comment]
@odeke-em Any icons or resources in general added to the project and are shipped and packaged with it just need to mention the license/documentation if possible. (assuming it's cool to ship to begin with).

But in the end any content that has permission is cool as far as I know. 

As far as actually packaging/updating idk lol. The debian/ubuntu package in the ppa is basically a one time snapshot.. so not sure how updating the icons would work otherwise.

**Comment by dgvirtual** [comment]
So I did make a pull request: took me some time to remember the little I knew (and used six year ago) of Git :) Hope I did make everything right.

**Comment by odeke-em** [comment]
Thank you @shaggytwodope for the suggestions, we'll need to get in touch to figure out how to get the users to install them.
Thank you @dgvirtual, good stuff. I've merged the PR with commit https://github.com/odeke-em/drive/commit/f8789c1ffd586f1dec1a0053dbf107b98be57e29

**Comment by odeke-em** [comment]
Btw @dgvirtual would you mind sharing with everyone how to get their icons installed possibly by writing an entry on the wiki? Thank you.

**Comment by shaggytwodope** [comment]
@odeke-em 

Two things of note Ithink need to be mentioned:
missing .dekstop extension, so it's basically treated like a plain text file currently.
not executable, needs to be set to execute ofc.


In regards to the icons themselves tho what we can do is just place the icons in an agreed path and hard link the icon path such as

Icon=/usr/share/pixmaps/application-vnd.google-apps.spreadsheet.png

This way, and Someone PLEASE correct me... the icons stay in place and aren't effected by people changing themes about.
As far as installing them goes tho, it's trivial to just copy the .png files on over and place in the dir mentioned above in debian/arch packages.
maybe a simple extra direction for the people doing this manually like sudo cp *.png /usr/share/pixmaps (or whatever) the agreed path is.

There may be some kinda spec to just use the file name without specific path. OR maybe even set a fallback icon (which would also be ideal if possible)

related links to check out:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html


And of some personal note, while I like and support the idea of using a custom "drive" set of icons. It may be much simpler in the end to simply use some system file type icons based on the spec mentioned above in the links. (Don't hate me, just an opinion lol)

I'll look into it more tomorrow evening, it's late and I'm tired lol. I've released the latest release without icons for now. But I will update later once we can fix/address some of this.

**Comment by odeke-em** [comment]
@shaggytwodope sorry for the late reply. Good catch yes in deed currently without the extension the files are being treated as text files, I had been previously informed that the extension didn't matter but I guess it does at least while we haven't yet found a way to.
I hear ye, and don't worry I understand how tiring weekends can get hehe.
Please let me know what you find. I'll probably be pushing up a change over the week after doing some more little research with the links you've provided, but for now school essays and assignments are calling on me.

**Comment by dgvirtual** [comment]
In my particular case, I have copied the icons I have made to ~/.local/share/icons

For testing purposes, I have made three Google documents and pulled them from the Cloud:

    Test Doc
    Test Draw
    Test Sheet    

Then I have made copies of those files with extension *.desktop

    Test Doc.desktop
    Test Draw.desktop
    Test Sheet.desktop

Then I took a regular *.desktop file as produced by Dolphin file manager, with the regular referenced icon, made also extensionless version:

    Test regular link
    Test regular link.desktop

Then I copied the Google document link file "Test Doc" and hardcoded the link to icon into it (full path, relative path did not work), changed the 

    Icon=application-vnd.google-apps.document
into 
    Icon=/home/dg/.local/share/icons/application-vnd.google-apps.document.png

(again, both extensionless version and a version with extension): 

    Test Doc hardcoded
    Test Doc hardcoded.desktop    

All these files can be found here: https://googledrive.com/host/0B7N4UaoQWBXiM1lod0ZRWFlfUlU

Then I tested how the files are displayed in four file managers: Dolphin, Nautilus, Thunar, PCmanFM (the screenshots of the tests are to be found in the same directory - see link above).

Dolphin and PCmanFM displayed all files as links, with icons. The expected behaviour :)

Nautilus displayed only files with extension as links, all with appropriate icons. The overlay icon for link (painted on the corner of the main icon) is missing on "Test Doc hardcoded.desktop" file, but it is still treated as a link upon click. The extensionless files are recognized as text. No recognition magic there.

Thunar displayed only files with extension as links, omitting (even in the hardcoded case) the icons. It seems that the file type overrides completely the internal Icon= directive in the file. 

Both Thunar and Nautilus on clicking the links complain that the file is not executable, but both offer a possibility to open the appropriate link or mark it executable. 

PCmanFM and Nautilus show the Name= parameter value instead of the file name in the *.desktop files. 

You have to bear in mind that I did not test it with the full desktop environments (Nautilus=Unity/Gnome, Thunar=XFCE, PCmanFM=?) – I just installed the file managers with the minimum dependencies, my regular desktop environment is Ubuntu. Could it be that the magic file content recognition is turned on upon more dependencies coming in?

Someone has to test these files on Gnome, Unity, XFCE and other desktop environments and post results here for better understanding. 

If any conclusions can be made, one would be that hardcoding icon paths gives no effect, and it is possible that adding *.desktop extension to the Google Doc files would make them somewhat user-friendlier. 


Another interesting thing is, that the file command recognizes both files with and without extensions as simple text files (while image files are recognized as image files – with or without extension). 

    dg@bala:~/Debesys/Drive/testdir/desktop$ file Test\ Doc
    Test Doc: ASCII text
    dg@bala:~/Debesys/Drive/testdir/desktop$ file Test\ Doc.desktop
    Test Doc.desktop: ASCII text

So it may be that the difference between plain text and plain text desktop file is not part of common Linux magic file type recognition, but depends on particular file managers or desktop environments.

**Comment by odeke-em** [comment]
Nice this is a good investigation. I can't elaborate much as I am up late. However, would you mind sharing this knowledge on the wiki so that folks will be to navigate through their setups. I too could use this information pretty soon :)

**Comment by odeke-em** [comment]
Update: I got a heads up from the Google Open Source Programs Office that the icons @dgvirtual made are good to go :)

**Comment by dgvirtual** [comment]
Great, they must have appreciated my wonderful art :)

**Comment by shaggytwodope** [comment]
@odeke-em So from a bit of searching, it seems the two best ways to go about this is either hardcoded paths, or placing the icons in the existing theme hicolor, this seems to be the common practice for most programs. I'll make a mockup install later this week when time allows. Life sucks when you get busy lol.

**Comment by odeke-em** [comment]
Good stuff @shaggytwodope, I hear ye on being busy. Otherwise, would y'all mind if we moved the discussion to issue #145?

**Comment by dgvirtual** [comment]
I have discovered xdg-mime, unlike file command, reports the file type of *.desktop files correctly, and I have updated the [comment](https://github.com/odeke-em/drive/issues/74#issuecomment-87616635) above.

**Comment by danielskapunk** [comment]
have you seen how InSync solves this?
I think it would be cleaner to not create a zero byte file and instead of a .desktop file create a .gdoc or .gddoc

![vsinsync](https://user-images.githubusercontent.com/289055/75709158-bf6aa880-5c87-11ea-8604-01735ded8950.png)
